name: Prod Deploy

on:
  push:
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn firebase deploy --project adventurecard-game --token ${{ secrets.FIREBASE_TOKEN }}
#      - name: Steam Upload
#        run: |
#          curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf -
#          ls -lah
#          ./steamcmd.sh +quit
#          ls -lah
#          pwd
#          mkdir config
#          echo '${{ secrets.STEAM_CONFIG }}' | base64 -d > $HOME/Steam/config/config.vdf
#          echo '${{ secrets.STEAM_CREDENTIAL }}' | base64 -d > ssfn27522370558009133
#          ./steamcmd.sh +login ${{ secrets.STEAM_LOGIN }} +quit
