name: Test Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: >
       sudo apt install steamcmd
       steamcmd login ${{ secrets.STEAM_LOGIN }} ${{ secrets.STEAM_PASSWORD }}
    - run: yarn firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
